### ISSUE TITLE
Unable to add Mazowsze i Ziemia Łódzka

### ISSUE THREAD

**Issue by muchar** [bieniu/ha-zadnego-ale#6]
When selecting "Mazowsze i Ziemia Łódzka" from selection list, there is an error "User input malformed".

**Comment by bieniu** [comment]
Which version of integration? Which version of HA?
I can't reproduce this problem, please provide a debug log. You have to add `logger` configuration to your `configuration.yaml` file:
```yaml
logger:
  default: warning
  logs:
    custom_components.zadnego_ale :debug
    zadnegoale: debug
```
